" allow beeing incompatible to vi
set nocompatible

" indentation
set shiftwidth=4
set tabstop=4
set expandtab
set autoindent

set ignorecase
set smartcase

set hlsearch " highlight search 

" allow use of mouse
set mouse=a
set ttymouse=xterm2

" line number
set number

" remove the '|' sign in vertical window seperator bar
set fillchars+=vert:\ 

syntax on

autocmd FileType make set noexpandtab

" Force correct coding style for some projects ... 
autocmd BufNewFile,BufRead */linux/* set noexpandtab tabstop=8 shiftwidth=8 textwidth=78
autocmd BufNewFile,BufRead */blender/* set noexpandtab tabstop=8 shiftwidth=8 textwidth=120


colorscheme monokai
